[package]
name = "advent-of-code"
authors = ["Felipe Garcia <felipefegar@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
itertools = "0.10.1"
num = "0.4.0"
rayon = "1.5.1"
regex = "1.5.4"
